CCDNForum\ForumBundle\Entity\Forum:
    # We are using "mappedSuperclass" here to allow to optionally create inherited entity classes and this way add your
    # own custom fields. This is possible by using the "ResolveDoctrineTargetEntitiesPass" compiler pass and the
    # "LoadORMMetadataSubscriber" listener.
    type: mappedSuperclass
    table: cc_forum_forum
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            unique: true
        readAuthorisedRoles:
            type: array
            column: read_authorised_roles
            nullable: true
    oneToMany:
        categories:
            targetEntity: CCDNForum\ForumBundle\Entity\Category
            mappedBy: forum
            cascade: ["persist", "remove"]
