CCDNForum\ForumBundle\Entity\Registry:
    # We are using "mappedSuperclass" here to allow to optionally create inherited entity classes and this way add your
    # own custom fields. This is possible by using the "ResolveDoctrineTargetEntitiesPass" compiler pass and the
    # "LoadORMMetadataSubscriber" listener.
    type: mappedSuperclass
    table: cc_forum_registry
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        cachedPostCount:
            type: integer
            column: cached_post_count
            nullable: false
        cachedKarmaPositiveCount:
            type: integer
            column: cached_karma_positive_count
            nullable: false
        cachedKarmaNegativeCount:
            type: integer
            column: cached_karma_negative_count
            nullable: false
    manyToOne:
        ownedBy:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_owned_by_user_id
                referencedColumnName: id
                onDelete: SET NULL
